# fly.toml app configuration file generated for new-word-everyday-back on 2025-07-15T19:49:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-word-everyday-back'
primary_region = 'gig'

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'
    method = 'get'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
