# fly.toml app configuration file generated for new-word-backend-v3 on 2025-09-29T12:39:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-word-backend-v3'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile.simple'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    method = 'get'
    path = '/'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
